### ISSUE TITLE
Can't set password when the value of cluster.enabled is yes

### ISSUE THREAD

**Issue by ganbing518** [ran-jit/tomcat-cluster-redis-session-manager#10]
if use redis cluster in project, why not support the password of redis?

**Comment by ganbing518** [comment]
JedisCluster(Set<HostAndPort> jedisClusterNode, int connectionTimeout, int soTimeout, int maxAttempts, String password, GenericObjectPoolConfig poolConfig) {

**Comment by ran-jit** [comment]
Hi @ganbing518 

I will check and update you ASAP.

Thanks,
Ranjith

**Comment by ran-jit** [comment]
Hi @ganbing518 

The fix is available in 2.0.3 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.3). I request you to kindly upgrade your session manager from version x to 2.0.3.

Thanks!
