### ISSUE TITLE
Session time default to 30 min

### ISSUE THREAD

**Issue by Sreelalitha-sapna** [ran-jit/tomcat-cluster-redis-session-manager#11]
HI 
i am using tomcat8.5
i tomcat-cluster-redis-session-manager with my application,
i have increased session time out at /tomcat/conf/web.xml
but redis session showing as key will expire in 1800 sec
please help me 
thanks in advance

**Comment by ran-jit** [comment]
Hi @Sreelalitha-sapna,

I will check the same and update you ASAP.

Thanks!

**Comment by ran-jit** [comment]
Hi @Sreelalitha-sapna 

The fix is available in 2.0.4 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.4). I request you to kindly upgrade your session manager from version x to 2.0.4.

Thanks!
