### ISSUE TITLE
Error occured while de-serializing the session object

### ISSUE THREAD

**Issue by ced1967** [ran-jit/tomcat-cluster-redis-session-manager#12]
Hi,

I'm getting this error:

SEVERE: Error occured while de-serializing the session object..
java.lang.ClassCastException: tomcat.request.session.SessionMetadata cannot be cast to tomcat.request.session.SessionMetadata
	at tomcat.request.session.SerializationUtil.deserializeSessionData(SerializationUtil.java:107)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:226)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:1)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2868)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2521)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:429)
	at tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:37)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

when the session is restored.
The data seems ok in redis but there's no way to solve this problem.
Can you help me?

Thanks in advance.

**Comment by ran-jit** [comment]
Hi @ced1967 

Which version of redis-session-manager are you using ?

At the same time, I will try to reproduce this issue in latest version.

Thanks!

**Comment by ced1967** [comment]
Hi, 

I'm using the last available version (2.0.4).
Thanks!

**Comment by ran-jit** [comment]
you are getting this error always or ?

**Comment by ced1967** [comment]
Yes, it happens all the time. Let me try to export the data.
By the way, I'm using Tomcat 8.0.29

**Comment by ced1967** [comment]
[Archive.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/2007962/Archive.zip)

Here they are.

Is strange because seems to create two sessions (?) and then when the object must be deserialized the session id is null...

Also the serializeSessionData generates different contents (480 bytes and 363)

**Comment by ced1967** [comment]
I'm debugging and the difference of bytes is because the _afterRequest_ method saves again the data. So, when the session is created from scratch then has no values. Later on some of them are set in my code:

session.setAttribute(CoreTags.USER_ALIAS_SESSION, alias);
session.setAttribute(CoreTags.LANGUAGE_INPUT_VAR, lang);

and the _afterRequest_ invocation explains that extra bytes

**Comment by ced1967** [comment]
I suspect that the maybe the problems is here:

ObjectInputStream ois = new CustomObjectInputStream(bis, this.loader)

The contents of the data seems OK, but this method isn't able to return an instance of SessionMetadata class. I've modified slightly your code (by the way very clear) to check this:

```
Object x=ois.readObject();
if(x instanceof SessionMetadata) {
  SessionMetadata serializedMetadata = (SessionMetadata) ois.readObject();
  metadata.copyFieldsFrom(serializedMetadata);
 session.readObjectData(ois);
}

```

and never passes the _"if"_

**Comment by ced1967** [comment]
I've tested with Tomcat 8.0.52 and the result is the same

**Comment by ran-jit** [comment]
Hi @ced1967 

I've replicated the same environment in my local machine and tried to reproduce the issue, working fine.

java version: 1.8.0_131
tomcat: 8.0.29

Today I will try to reproduce the issue with the enclosed redis data and update you.

Thanks!

**Comment by ced1967** [comment]
It would be a good improvement non being necessary to copy the jars to tomcat/lib folder. In a cloud environment (Azure) is pretty difficult to manage this stuff (due to deployment, scalability, etc. reasons)

**Comment by ran-jit** [comment]
Hello,

Which version of java are you using ?

I'm suspecting the issue is because of java version. Latest 2.0.4 version I've built from java 1.8 version.

**Comment by ran-jit** [comment]
I've created a new session-manager, please replace the extracted enclosed file in tomcat/lib directory and check the same.

[tomcat-cluster-redis-session-manager-2.0.4.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/2018992/tomcat-cluster-redis-session-manager-2.0.4.zip)

Thanks!

**Comment by ran-jit** [comment]
Reg: Production deployment.

My production environment setup:

I've added new directory in catalina common.loader (tomcat/conf/catalina.properties) and copied the session manager .jar files to tomcat/lib/external directory
  * ex: ${catalina.home}/lib/external,${catalina.home}/lib/external/*.jar

Hope this helps!

**Comment by ran-jit** [comment]
Any update ?

**Comment by ced1967** [comment]
Hi,

sorry but I'm not in the office this days and I can't check anything. I promise I'll get all the stuff and do some testing asap. Thanks a lot for you support.

**Comment by ced1967** [comment]
When you say:

_"I've added new directory in catalina common.loader (tomcat/conf/catalina.properties) and copied the session manager .jar files to tomcat/lib/external directory

ex: ${catalina.home}/lib/external,${catalina.home}/lib/external/*.jar"_

My problem is I can't modify ANY Tomcat configuration file. Actually the ideal scenario will be that your jar file was only in the WEB-INF folder of the app itself.

**Comment by ran-jit** [comment]
I hope the shared one is working fine. (Ref: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/13)

**Comment by ran-jit** [comment]
Reg the prod deployment,

If you keep the session-manager jar file in your .war/WEB-INF/lib directory, tomcat will throw class not found "tomcat.request.session.redis.SessionHandlerValve" exception in startup (Reason: WEB-INF directory is specific to the .war file).

In this session manager, we're customizing tomcat catalina session valve and manager for storing session data from internal context to redis. This is more specific to the tomcat, so the below changes are mandatory for enabling this session manager in your environment.

Steps to be done,

1. Move the downloaded jars to tomcat/lib directory
       tomcat/lib/

2. Add tomcat system property "catalina.base"
       catalina.base="TOMCAT_LOCATION"

3. Extract downloaded package (tomcat-cluster-redis-session-manager.zip) to configure Redis credentials in redis-data-cache.properties file and move the file to tomcat/conf directory
       tomcat/conf/redis-data-cache.properties

4. Add the below two lines in tomcat/conf/context.xml
       &#60;Valve className="tomcat.request.session.redis.SessionHandlerValve" &#47;&#62;
       &#60;Manager className="tomcat.request.session.redis.SessionManager" &#47;&#62;

**Comment by ced1967** [comment]
Hi,

that are bad news for me... we're working with Tomcat (native) under Azure and all this kind of configuration is not easy to scale/maintain (as I said before).

We're considering not to use the "native" approach. This means that we could use your library by copying the jars in tomcat/lib.

Anyway, I've modified your code to read the parameters directly on the context.xml file.

Example:

<Manager className="tomcat.request.session.redis.SessionManager" host="my_host" password="my-pwd" 
  	ssl="true" clusterEnabled="false" timeout="60000" />

Note that the ssl protocol can be activated.

If you're interested I can send you the code.

Thanks again for your support.

**Comment by ced1967** [comment]
[tomcat.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/2031710/tomcat.zip)

The changes are basically in : 
   - SessionManager

 There are new properties like host, ssl, etc. plus getters/setters.

- RedisDataCache

 Instead of reading an external file, I set the properties like this:

   ```
Properties properties = new Properties(); 
properties.put(RedisConstants.HOSTS,sessionManager.getHost());
properties.put(RedisConstants.PASSWORD,sessionManager.getPassword()); 
properties.put(RedisConstants.TIMEOUT,sessionManager.getTimeout()); 
properties.put(RedisConstants.CLUSTER_ENABLED,sessionManager.getClusterEnabled()); 
```

The context.xml file (in META-INF folder) contains all the stuff:

```
<Valve className="tomcat.request.session.redis.SessionHandlerValve" />
<Manager className="tomcat.request.session.redis.SessionManager" host="myhost:6380" password="my-pwd" 
  	ssl="true" clusterEnabled="false" timeout="60000" />
```
