### ISSUE TITLE
Deserialization Exception while redirecting to another application

### ISSUE THREAD

**Issue by achappan** [ran-jit/tomcat-cluster-redis-session-manager#13]
I am getting deserialization exception while redirecting to the another application which is existing in another tomcat server.

Kindly suggest to resolve this issue.

HTTP Status 500 - Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 420, local class serialVersionUID = 320

**Comment by ran-jit** [comment]
Hi @achappan 

Sorry for my delayed response.

Which version of java and redis-session-manager are you using ?

**Comment by ran-jit** [comment]
I've created a new session-manager, please replace the extracted enclosed file in tomcat/lib directory and check the same.

[tomcat-cluster-redis-session-manager-2.0.4.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/2018992/tomcat-cluster-redis-session-manager-2.0.4.zip)

Thanks!

**Comment by ran-jit** [comment]
Any update ?

**Comment by achappan** [comment]
Thank you Ranjith. It got resolved by using the latest one.

**Comment by ran-jit** [comment]
Thanks @achappan

**Comment by ran-jit** [comment]
Note: I've updated the latest artifacts in release page.
