### ISSUE TITLE
RedisCacheUtil methods close jedis connection incorrect

### ISSUE THREAD

**Issue by yyoosn** [ran-jit/tomcat-cluster-redis-session-manager#14]
public byte[] set(String key, byte[] value) {
			int tries = 0;
			boolean sucess = false;
			String retVal = null;
			do {
				tries++;
				try {
					Jedis jedis = pool.getResource();
					retVal = jedis.set(key.getBytes(), value);
					jedis.close();
					sucess = true;
				} catch (JedisConnectionException ex) {
					log.error(RedisConstants.CONN_FAILED_RETRY_MSG + tries);
					if (tries == NUM_RETRIES)
						throw ex;
				}
			} while (!sucess && tries <= NUM_RETRIES);
			return (retVal != null) ? retVal.getBytes() : null;
		}

try catch体内调用jedis.close(); 很可能导致 不能正常关闭，是否在finally内调用?
bug现象为tomcat 产生很多CLOSE_WAIT的tcp连接，怀疑和这段代码有关
使用的是redis单点服务，redis集群则没有这种情况

**Comment by ran-jit** [comment]
Hi @yyoosn,

I will look into this and update you.

Thanks!

**Comment by ran-jit** [comment]
Hi @yyoosn,

I tried multiple ways to break this code, working fine as expected. Please describe the scenario you faced the issue with this code.

Thanks!

**Comment by ran-jit** [comment]
Hi @yyoosn,

Closing this issue. Please reopen if you find any issues.

Thanks!

**Comment by yyoosn** [comment]
i'm sorry, I think you may be a chinese. And i'm wrong you are Indian。
My english is poor，so never mind。
this issue I emphasized that jedis connection had wrong way to close，jedis.close()  inside try catch isn't necessarily work。you should put it in finally{}。if jedis haven‘t been closed，this may always hold on tomcat tcp connections util tcp status is  CLOSE_WAIT；a lot of CLOSE_WAIT tcps will course tomcat feign death.
I think the code you updated still have some problem though that i haven't test it。
  public byte[] set(String key, byte[] value) {
    int tries = 0;
    boolean sucess = false;
    String retVal = null;
    do {
      tries++;
      try (Jedis jedis = pool.getResource()) {
        retVal = jedis.set(key.getBytes(), value);
        sucess = true;
      } catch (JedisConnectionException ex) {
        log.error(RedisConstants.CONN_FAILED_RETRY_MSG + tries);
        if (tries == NUM_RETRIES) {
          throw ex;
        }
      }
    } while (!sucess && tries <= NUM_RETRIES);
    return (retVal != null) ? retVal.getBytes() : null;
  }
 At this time jedis isn't closed any way?
 And i think add finally body to close jeids will be better.
  
      Jedis jedis = null;
      try {
        jedis = pool.getResource()
        retVal = jedis.set(key.getBytes(), value);
        sucess = true;
      } catch (JedisConnectionException ex) {
        log.error(RedisConstants.CONN_FAILED_RETRY_MSG + tries);
        if (tries == NUM_RETRIES) {
          throw ex;
        }
      }finally {
        if(jedis!=null){
          jedis.close();
        }
      }
