### ISSUE TITLE
When Redis goes down, the web app always fails returning failure

### ISSUE THREAD

**Issue by babujoym** [ran-jit/tomcat-cluster-redis-session-manager#19]
Hi,

I was just checking how the server will behave when the redis server is down. Should it continue to accept web requests.

However I noted that, once the redis server is down, all the web requests are returned 500... 
Is there something I should do.

**Comment by ran-jit** [comment]
Hi @babujoym,

If the Redis server is down, session handler throw the exception. So you're getting the 500 - Internal server error for all the requests.

This manager is designed for the distributed environment.

First level (request reached to tomcat server) all the request session values are updated from redis to request session context (redis stored values are the updated session values). So redis-server is down, requests will not be forwarded to the next level.

Thanks!

**Comment by posondlq** [comment]
If nginx has done session preservation, can redis be crossed ，but  the application run properly, so that session sharing does not affect the whole application? Because ,sometimes session sharing is used to ensure serial upgrades, and front-end WEB applications are not affected.

**Comment by babujoym** [comment]
Yes I can see that the manager is designed for distributed environment and yes it doesn't make much sense to get data from normal local session as the requests can come to any of the distributed tomcats and fail. 

What do you think about as a backup provide tomcat session replication, but i heard it takes a long time and not efficeant.

**Comment by ran-jit** [comment]
Yep, tomcat session replication is not performant/efficient and cloud (VPC) environment (ex: AWS, GCP) they will not allow to share the data through network.

Secondly tomcat session replication internally uses File store or JDBC store. Reading data from File/Database will take time compare to redis (in-memory cache).

**Issues I've faced with tomcat session replication:**
1. We've to enable sticky session (JSESSIONID) in your load balancer configuration. In this case, one of your tomcat node is down, LB take some time for forwarding the request to next tomcat node. Sometimes end users ll end up with blank page because of request timeout in internet fluctuation.
2. Sometimes file store throw Files not responding/Files not open issue.

**Comment by ran-jit** [comment]
Closing this issue. Please feel free to re-open this or create new issues in future.

Thanks!

**Comment by posondlq** [comment]
In the current way, if redis is crossed, applications can not be accessed. Once this happens, if we can not resume redis cluster in a short time, we can only cancel session sharing first, and i verify it is feasible. So it is still possible to support some configuration. When the LB support  sticky session ,When redis cluster is across, applications can continue to run.

**Comment by ran-jit** [comment]
@posondlq,

Yep, we can..

Redis-cluster has minimum of 3 nodes in the cluster group. If all 3 nodes are down then you will not get session related data from the redis cache. Also if all 3 nodes are down, then something you're missing in configuration/env.

I think if we implement that with feature flag, that will reduce the redis data read. I will look into this and revert the updates soon.

**Comment by ran-jit** [comment]
Hi @posondlq,

I've modified the changes and updated a [pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0) (version: 3.0)

Please add '**lb.sticky-session.enabled**' property in '**redis-data-cache.properties**' configuration and enable this feature.

If enabled,
1. Must be enabled sticky session in your load balancer configuration. Else this manager may not return the updated session values.
2. Session values are stored in local jvm and redis.
3. If redis is down/not responding, requests uses jvm stored session values to process user requests. Redis comes back the values will be synced.

I've tested in standalone redis env and don't have cluster env ready. If you've cluster enabled test env and time, please check..

Thanks!

**Comment by babujoym** [comment]
Thanks That's great.. Its a good addition
