### ISSUE TITLE
how to do debug the programs with the test class

### ISSUE THREAD

**Issue by posondlq** [ran-jit/tomcat-cluster-redis-session-manager#20]
Hi，how to do debug the programs with the test class。

**Comment by ran-jit** [comment]
Hi @posondlq,

Steps to be done,
1. Create new Java enterprice/dynamic web application.
2. Copy the test class to that project.
<img width="1111" alt="pic-1" src="https://user-images.githubusercontent.com/8708711/49249434-1e68be80-f442-11e8-85e9-1bad1c38286c.png">

3. Configure your tomcat server with the [tomcat-cluster-redis-session-manager](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/blob/master/README.md).
4. Add you created application to the tomcat server.
5. Start tomcat server in debug mode. (reference: pic-2
<img width="1118" alt="pic-2" src="https://user-images.githubusercontent.com/8708711/49249435-1e68be80-f442-11e8-9a87-7000000e133b.png">

Hope it helps!!

Thanks!
