### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlbertYangg** [ran-jit/tomcat-cluster-redis-session-manager#22]
Error occured while saving the session object in data cache.. -tomcat.request.session.redis.SessionManager
java.io.NotSerializableException: java.lang.Object

**Comment by ran-jit** [comment]
Hi @AlbertYangg,

This session manager accepts only the Serializable objects. If you try to set session with non-serializable object (value) you will get this exception.

Reference: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/21

 Note: All your session attribute values must implement java.io.Serializable.

Thanks!
