### ISSUE TITLE
Session timeout default to 1800s ,can not be lower

### ISSUE THREAD

**Issue by hequanb** [ran-jit/tomcat-cluster-redis-session-manager#23]
When I set session timeout with 
`
    <session-config>
        <session-timeout>2</session-timeout>
    </session-config>
`
I find that timeout can not be set lower than 30 minutes(1800 s).
so is the redis TTl(1800s).
Is that a bug ? Or just something else?
Thanks.

**Comment by ran-jit** [comment]
Hi @hequanb,

I've faced issues with redis ttl in cluster and sentinel environments, so the default/lower timeout value is 30mins (1800 sec).

Thanks!

**Comment by hequanb** [comment]
GOT THAT. Thanks for replying.
