### ISSUE TITLE
Web application is throwing 500 internal server error for the very first http request, due to uncertainity of the redisdb instance (redisdb instance may be down or it might be configured to read only access) 

### ISSUE THREAD

**Issue by das-devi** [ran-jit/tomcat-cluster-redis-session-manager#29]
Hi Ranjit,

I was playing with your solution for sharing session in cluster of tomcat servers by deploying a web application in multiple servers , this solution is awesome, however i came across one challenge, that is as below.

Due to some uncertainty of the redisdb instance, instance may not be up, or it may be configured with  read only access, in this case when i deploy my war file and hit very first time http request to my server to access welcome page of my application

Due to unavailability of the redisdb instance or if it has only read only access application is getting stopped due to 500 internal server error thrown by api's of tomcat-cluster-redis-session-manager.jar  in tomcat server.

is there any option in this solution?.  like if any such redisdb instance errors occurs  can it be ignored by exception handling ?. to avoid 500 internal server error.....and let the  http request served successfully without any error.

due to properly unavailability of redisdb instance entire application is going down. 
(in this case we no need of session sharing at least expecting our application should up and running fine )

**Comment by ran-jit** [comment]
Hi @das-devi,

If the Redis server is down, the session handler throw the exception. So you're getting the 500 - Internal server error for all the requests.

**Reason:**
This manager is designed for the distributed environment.

The first level (request reached to tomcat server) all the request session values are updated from redis to request session context (redis stored values are the updated session values). So redis server is down, requests will not be forwarded to the next level.

We came up with temp session storage with feature flag.

'**lb.sticky-session.enabled**' property in '**redis-data-cache.properties**' configuration enable this feature.

If enabled,
1. Must be enabled sticky session in your load balancer configuration. Else this manager may not return the updated session values.
2. Session values are stored in local jvm and redis.
3. If redis is down/not responding, requests use jvm stored session values to process user requests. Redis comes back the values will be synced.

Changes: [pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0) (version: 3.0)

FYI: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/19

I hope this helps. Thanks!

**Comment by das-devi** [comment]
Thanks Ranjith for your quick update.

i tried by setting 'lb.sticky-session.enabled=true' getting the below exception (in this case my redisdb instance is down).


 redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

please find the below attached screen shot for more details on the error

![session-replication](https://user-images.githubusercontent.com/36114359/51631842-cb0f7a00-1f73-11e9-92ba-188e93752243.png)

**Comment by das-devi** [comment]
Steps to reproduce the above issue are as below.

if i don't turn on my redisdb instance and start tomcat and try to access the application getting 500 internal server error.

tried one more scenario

turn on the redisdb instance and start tomcat and access the application and access few pages and turn of the redisdb instance , the subsequent request are still getting served successfully.

above issue i am able to see during very first time when i start the tomcat with redisdb is down.

**Comment by ran-jit** [comment]
Hi @das-devi,

https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/29#issuecomment-456936679 is the expected behaviour.

**Reason:** Application startup the code internally checks the redis nodes health check and this implementation handles only the redis down at runtime. 

The server cache the session values for some time and once the redis server back, values LL be updated to redis (master data).

Thanks!

**Comment by das-devi** [comment]
thanks a lot...!!!! for your quick updates and it helped me a lot. 
closing the issue.
