### ISSUE TITLE
logout error

### ISSUE THREAD

**Issue by moogor** [ran-jit/tomcat-cluster-redis-session-manager#30]
Clearing the session state failed while executing the `Session.invalidate();`.

**Comment by ran-jit** [comment]
Hi @moogor,

I tried to reproduce the issue in my dev env, working fine.

Please share me the tomcat version, i will check the same.

Thanks!

**Comment by moogor** [comment]
> Hi @moogor,
> 
> I tried to reproduce the issue in my dev env, working fine.
> 
> Please share me the tomcat version, i will check the same.
> 
> Thanks!

tomcat 8.5.35

Can't delete `session key` using `del` method?

**Comment by ran-jit** [comment]
Hi @moogor,

I've tested "request.getSession().removeAttribute(key);" in tomcat 8.5.35 version. Working fine as expected.

**Tested env configuration:**
* Tomcat version: apache-tomcat-8.5.35
* Session manager version: 3.0
<img width="787" alt="screenshot 2019-01-30 at 10 31 20 pm" src="https://user-images.githubusercontent.com/8708711/51998496-ccdebd80-24de-11e9-8ce3-5dfa5a61af36.png">

Please check the same from your end and let me know.

Thanks!

**Comment by moogor** [comment]
> Hi @moogor,
> 
> I've tested "request.getSession().removeAttribute(key);" in tomcat 8.5.35 version. Working fine as expected.
> 
> **Tested env configuration:**
> 
> * Tomcat version: apache-tomcat-8.5.35
> * Session manager version: 3.0
> 
> <img alt="screenshot 2019-01-30 at 10 31 20 pm" width="787" src="https://user-images.githubusercontent.com/8708711/51998496-ccdebd80-24de-11e9-8ce3-5dfa5a61af36.png">
> 
> Please check the same from your end and let me know.
> 
> Thanks!

The jar file is shown above. The environment variables are the same. The version is also. But my project is to run multiple projects with multiple tomcats. Then use Nginx as a reverse proxy.

**Comment by ran-jit** [comment]
Hi @moogor,

Sorry for my late response. I created the same environment and tested with multiple tomcat servers. It's working fine.

If still the issue persists, please reproduce the same and share me the logs.

Thanks!

**Comment by ran-jit** [comment]
Closing this issue. Please feel-free to reopen this issue/create new issue, if you require additional details in future.
