### ISSUE TITLE
logout defautl ttl 10

### ISSUE THREAD

**Issue by K-Gamine** [ran-jit/tomcat-cluster-redis-session-manager#32]
The default value of ttl, which changes to redis when you log out, is 10. Is there a way to modify this value?

**Comment by ran-jit** [comment]
Hi @K-Gamine,

I've [modified](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/commit/b3bdf8308cf63ab6550b85b57d2d70541296998c
) the code. Please give me some time I will build the changes and update you.

Thanks!

**Comment by K-Gamine** [comment]
An error related to dependencies occurs during the build.
Sorry, can I get files built with modified code?

**Comment by K-Gamine** [comment]
> Hi @K-Gamine,
> 
> I've [modified](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/commit/b3bdf8308cf63ab6550b85b57d2d70541296998c) the code. Please give me some time I will build the changes and update you.
> 
> Thanks!

An error related to dependencies occurs during the build.
Sorry, can I get files built with modified code?

Could not resolve dependencies for project tomcat-cluster-redis-session-manager:tomcat-cluster-redis-session-manager:jar:3.0: The following artifacts could not be resolved: apache-tomcat:catalina:jar:apache-tomcat-8.5.32, apache-tomcat:servlet-api:jar:apache-tomcat-8.5.32, apache-tomcat:tomcat-api:jar:apache-tomcat-8.5.32: Failure to find apache-tomcat:catalina:jar:apache-tomcat-8.5.32 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project tomcat-cluster-redis-session-manager: Could not resolve dependencies for project tomcat-cluster-redis-session-manager:tomcat-cluster-redis-session-manager:jar:3.0: The following artifacts could not be resolved: apache-tomcat:catalina:jar:apache-tomcat-8.5.32, apache-tomcat:servlet-api:jar:apache-tomcat-8.5.32, apache-tomcat:tomcat-api:jar:apache-tomcat-8.5.32: Failure to find apache-tomcat:catalina:jar:apache-tomcat-8.5.32 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by ran-jit** [comment]
Hey @K-Gamine,

The fix is available in 3.0.1 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.1). Please upgrade your session manager from version x to 3.0.1.

Thanks!

**Comment by K-Gamine** [comment]
Thank you.
Everything works fine.

have a nice day
