### ISSUE TITLE
session.invalidate is not working

### ISSUE THREAD

**Issue by hiake21cKakao** [ran-jit/tomcat-cluster-redis-session-manager#34]
session invalidate does not work after applying redis-session lib.
and then also JSESSION ID is not change.

I'm using Tomcat 8.5.40 and

here ls my code.

HttpSession session  = request.getSession();
session.removeAttribute("logonSessData");
session.invalidate();

**Comment by ran-jit** [comment]
Hey @hiake21cKakao,

Which version of session manager you're using?

**Comment by hiake21cKakao** [comment]
I’m using 3.0 version now.

**Comment by ran-jit** [comment]
Recently I've updated session removal changes in 3.0.1 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.1). Please, update your session manager from version 3.0 to 3.0.1 and check the same.

I hope it works!

**Comment by hiake21cKakao** [comment]
I’m going to check it right now. And then I will let you know it works or now. Thanks for fixing the bug :)

**Comment by hiake21cKakao** [comment]
it's working good :) and then I checked when session.invalidate(); 
When I try session invalidated, I checked redis key erased the session well.
 
thanks.

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue. Thanks!
