### ISSUE TITLE
How get I set redis pool connection configration?

### ISSUE THREAD

**Issue by hiake21c** [ran-jit/tomcat-cluster-redis-session-manager#36]
There is no way change redis connection pool configuration value.

I saw into the  source. it set 5 connection pool. 

but I think it is not enough large scale running environment.

it should be possible to change.

**Comment by ran-jit** [comment]
Hi @hiake21c,

It's configurable.

To customize your Redis connection pool, please add below properties in your **redis-data-cache.properties** config file.

```
redis.max.active=10
redis.test.onBorrow=true
redis.test.onReturn=true
redis.max.idle=5
redis.min.idle=1
redis.test.whileIdle=true
redis.test.numPerEviction=10
redis.time.betweenEviction=60000
```
I hope it helps!

**Comment by hiake21c** [comment]
Oh I will test it.  Thanks

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue. Thanks!
