### ISSUE TITLE
Session are not updating in to the redis

### ISSUE THREAD

**Issue by suryathejamamidi** [ran-jit/tomcat-cluster-redis-session-manager#38]
After implementing sessions are not saving into the redis,Please find the below error.

17-May-2019 17:38:53.771 SEVERE [http-nio-8080-exec-7] tomcat.request.session.redis.SessionManager.save Error occurred while saving the session object in data cache..
 java.io.NotSerializableException: org.apache.catalina.loader.ParallelWebappClassLoader

**Comment by ran-jit** [comment]
Hi @suryathejamamidi,

This session manager accepts only the Serializable objects. If you try to set session value with a non-serializable object you will get this exception.

<img width="664" alt="screenshot 2018-11-30 at 2 03 37 am" src="https://user-images.githubusercontent.com/8708711/49250160-2aee1680-f444-11e8-854b-3bd6ca0dd863.png">

**Resolution:** Please implement the classes with the Serializable interface.

<img width="703" alt="screenshot 2018-11-30 at 2 12 24 am" src="https://user-images.githubusercontent.com/8708711/49251068-90db9d80-f446-11e8-9802-5410224b72da.png">

**Reason:** We're converting an object (value) into a stream of bytes and storing it into Redis data cache. So please implement the classes with serializable and add the "serialVersionUID" (During serialization, java runtime associates a version number with each serializable classes. This number called serialVersionUID, which is used during deserialization to verify the serialized object).

I hope it helps!!

Thanks!

**Comment by suryathejamamidi** [comment]
hi @ran-jit 

Thanks for the info.
can you let me know  exact path of this file....?

**Comment by ran-jit** [comment]
Hi @suryathejamamidi,

This session manager accepts only the Serializable objects. So please implement the classes with serializable and add the "serialVersionUID" in your project files (The session value objects).

I hope it clear now!

Thanks!

**Comment by ran-jit** [comment]
Any update..?

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!
