### ISSUE TITLE
not working with jitpack

### ISSUE THREAD

**Issue by smacritchie** [ran-jit/tomcat-cluster-redis-session-manager#40]
Hi, I'm trying to install this with maven using jitpack.io but I'm getting compilation errors:
https://jitpack.io/com/github/ran-jit/tomcat-cluster-redis-session-manager/3.0.2/build.log
Do you know if this project works with jitpack?
Thanks,
Scott

**Comment by ran-jit** [comment]
Hi @smacritchie,

This project has internal tomcat dependencies of catalina.jar, servlet-api.jar and tomcat-api.jar. So please upload the catalina.jar, servlet-api.jar and tomcat-api.jar files in your repository and update the dependency in pom.xml.

<img width="410" alt="Screenshot 2019-06-26 at 10 25 33 AM" src="https://user-images.githubusercontent.com/8708711/60152080-cc7fef80-97fc-11e9-8f24-d93730abd7ab.png">

I hope it helps!

Thanks!

**Comment by ran-jit** [comment]
Any update ..?

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!
