### ISSUE TITLE
Session destruction

### ISSUE THREAD

**Issue by TAO-19** [ran-jit/tomcat-cluster-redis-session-manager#42]
Do you need to do this when session is destroyed and call the remove method in session manager when session is destroyed? Or in other ways

**Comment by ran-jit** [comment]
When setting up the Redis key, we set the timeout. So the destroyed sessions expire in Redis once they reach expiration time. So we didn't explicitly call the removal method.

**Comment by TAO-19** [comment]
Now we need to do the operation when the session fails. Do you have any good suggestions?

**Comment by ran-jit** [comment]
Please give me some time and I'll let you know.

**Comment by ran-jit** [comment]
This manager handles multiple Tomcat sessions, where one server fails, while the other server handles requests based on Redis session details. So if we explicitly remove session details, it is not the right way to go.

If you share a use case, I'll get some clarity on this.

**Comment by TAO-19** [comment]
Now you need to monitor the number of people online in redis, and you need to do something when the session fails.

**Comment by TAO-19** [comment]
Session failure Tomcat listener can not be monitored, is it considered to be a redis failure listener?

**Comment by TAO-19** [comment]
Session-invalid Tomcat listener can not be monitored, can we consider doing key-invalid listener in redis?

**Comment by ran-jit** [comment]
Hi @TAO-19,

Please give me some time and I'll think and let you know.

**Comment by ran-jit** [comment]
For monitoring the active sessions, I've created a new manager [SessionDetailsManager](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/blob/session-42/src/main/java/tomcat/request/session/manager/SessionDetailsManager.java), [Test reference](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/blob/session-42/src/test/java/tomcat/request/session/redis/SessionManagerTest.java).

If we call session invalidate or removeAttribute method, immediately session details are removed from Redis. Here if you want to perform the additional operation you can write your listener by extending HttpSessionListener.

PS- The changes are not in the master branch. Please let me know your thoughts on this.

Thanks!

**Comment by TAO-19** [comment]
The session manager fails session behavior after session sharing needs to be monitored

**Comment by TAO-19** [comment]
I would like to think about it
Thanks

**Comment by ran-jit** [comment]
Any update.. ?

Thanks!

**Comment by TAO-19** [comment]
I have found a solution. Thank you very much.
