### ISSUE TITLE
How to set SessionPolicy from properties?

### ISSUE THREAD

**Issue by monkeyk** [ran-jit/tomcat-cluster-redis-session-manager#43]
SessionManager.java have sessionPolicy field, but do not set it or config it?
except hard code  sessionPolicy values?
how to set it by properties?

**Comment by monkeyk** [comment]
![session-policy](https://user-images.githubusercontent.com/2149950/62849035-9943e200-bd10-11e9-9485-39e1734d49a2.jpg)

**Comment by monkeyk** [comment]
We found a bug if set sessionPolicy only DEFAULT value, because redis-session lost SavedReqeust data with Spring-Security framework. (must set sessionPolicy value to DEFAULT and SAVE_ON_CHANGE)

**Comment by ran-jit** [comment]
Hi @monkeyk,

I've modified the changes and updated a [pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.3) (version: 3.0.3)

Please add 'session.persistent.policies' property in 'redis-data-cache.properties' configuration and add the policies (DEFAULT, SAVE_ON_CHANGE, ALWAYS_SAVE_AFTER_REQUEST).

I hope it helps!

Thanks!

**Comment by monkeyk** [comment]
Got it
