### ISSUE TITLE
JedisPool.getResource() can cause blocked and fake death

### ISSUE THREAD

**Issue by guoZD** [ran-jit/tomcat-cluster-redis-session-manager#44]
![QQ截图20190812150833](https://user-images.githubusercontent.com/13429385/62849660-183a1a00-bd13-11e9-9267-f2de277bc8f3.png)
We need to solve the problem this way : poolConfig.setMaxWaitMillis(10 * 1000);

**Comment by guoZD** [comment]
使用的版本是tomcat-cluster-redis-session-manager-2.0.1

**Comment by ran-jit** [comment]
Hi @guoZD,

I've updated Redis changes in the latest release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.2). Please, update your session manager from version 2.0.4 to 3.0.2 and check the same.

I hope it works!

**Comment by 442114004** [comment]
very good

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!
