### ISSUE TITLE
The second step of this  catalina.base="TOMCAT_LOCATION".

### ISSUE THREAD

**Issue by comeCU** [ran-jit/tomcat-cluster-redis-session-manager#46]
Hi, @ran-jit  I have encountered some problems, now I got it.
1. My System environment is Centos7
2. The second step of this readme document

   - Add tomcat system property "catalina.base".
      - catalina.base="TOMCAT_LOCATION"
         - example: export catalina.base=/opt/tomcat
 
   **the "catalina.base" have a invalid symbol dot "."**

as follows : modify  **catalina.base to catalina_base**
---
- `vi /etc/profile`
- `export catalina_base=/your/opt//tomcat`
- `source /etc/profile`

thanks a lot !

**Comment by ran-jit** [comment]
Hi @comeCU,

I've updated the Readme file.

_env "catalina.base=/opt/tomcat" bash_

Thanks!

**Comment by ran-jit** [comment]
FYI: Tomcat internally adds the "catalina.base" system property in both debug and run mode. So it's optional.

<img width="789" alt="Screenshot 2019-09-04 at 10 12 43 PM" src="https://user-images.githubusercontent.com/8708711/64276347-5b2f8c00-cf65-11e9-974d-85e965d01ce0.png">

Thanks!
