### ISSUE TITLE
add the interpretation of variables in the configuration file redis-data-cache.properties

### ISSUE THREAD

**Issue by lepapareil** [ran-jit/tomcat-cluster-redis-session-manager#48]
Hi,

Thanks for this plugin that works perfectly :)

So I have a suggestion, just like the other tomcat conf files, it would be nice to be able to use java variables passed at tomcat startup to make dynamic the REDIS_PORT or REDIS_SERVER information, so in a docker context, the conf file would look like this

redis.hosts=${REDIS_SERVER}:${REDIS_PORT}

and deployment would be given the right value depending on the environment.
Currently I have to have a script that does sed before starting the tomcat :(

thanks :)

**Comment by ran-jit** [comment]
Hi @lepapareil,

Thank you very much for your suggestion.

Now we can use the system environment variable as direct values.

**redis-data-cache.properties**
1. redis.hosts=${REDIS_HOST}:${REDIS_PORT}
2. redis.cluster.enabled=${REDIS_CLUSTER_ENABLED}

Changes: [pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.4) (version: 3.0.4)

I hope this helps. Thanks!

**Comment by lepapareil** [comment]
Thks for your reactivity ! I'll test it as soon as possible :)

**Comment by ran-jit** [comment]
I tested new changes ([version: 3.0.4](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.4)) and it works fine :)

**Comment by lepapareil** [comment]
thks
