### ISSUE TITLE
session Data loss

### ISSUE THREAD

**Issue by TAO-19** [ran-jit/tomcat-cluster-redis-session-manager#53]
Use version 3.0，Load balancing, session data loss

**Comment by ran-jit** [comment]
Hey @TAO-19,

I've done some fixes in 3.0.1 and 3.0.2 related to the session. So I think if you upgrade your session manager to the latest version, this issue will be sorted out.

Please upgrade your session manager from 3.0 to [3.0.4](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.4) and check.

I hope this helps. Thanks!

**Comment by TAO-19** [comment]
Thank you. I tried. It seems that I can't. the data in some sessions will disappear after a period of time. I'm confused

**Comment by ran-jit** [comment]
Please check the `tomcat/conf/web.xml` session-config -> session-timeout.

```
<session-config>
        <session-timeout>60</session-timeout>
</session-config>
```

Based on the session-timeout setting the session values will be expired in Redis.

for example: above config case, after 60mins the session values will be removed in Redis.

I hope this helps. Thanks!

**Comment by TAO-19** [comment]
Session is effective, and data loss occurs during the use. Similar to the load condition, the data in the session is not shared, and the data is not refreshed to redis in time

**Comment by ran-jit** [comment]
I think some configuration is not correct. Please check the same, since you are only facing the issue.

1. https://github.com/ran-jit/tomcat-cluster-redis-session-manager#steps-to-be-done.
2. verify redis-data-cache.properties file permissions.
3. check tomcat start-up logs.

I hope this helps, otherwise, we can have call..

Thanks!

**Comment by TAO-19** [comment]
thank you.
I think I've found the root of the problem

**Comment by ran-jit** [comment]
what was the issue?

**Comment by TAO-19** [comment]
Multi request problem. At the same time, the request will be subject to the last request session

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!
