### ISSUE TITLE
NPE in SessionHandlerValve.java accessing Tomcat's /manager app

### ISSUE THREAD

**Issue by skehlet** [ran-jit/tomcat-cluster-redis-session-manager#54]
Hi there, I'm trying out your session manager (thanks!), but I get the following exception in my browser when I try to hit the `/manager` app:
```
java.lang.NullPointerException
	tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:34)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
```
I double checked with a fresh tomcat install:
* Download Tomcat 8.5.54 from https://tomcat.apache.org/download-80.cgi, untar/gzip
* Add the following to conf/context.xml:
```
    <Valve className="tomcat.request.session.redis.SessionHandlerValve" />
    <Manager className="tomcat.request.session.redis.SessionManager" />
```
* Copy commons-pool2-2.6.2.jar jedis-3.0.1.jar slf4j-api-1.7.26.jar tomcat-cluster-redis-session-manager-3.0.5.1.jar into lib
* cp redis-data-cache.properties to conf (no changes)
* ./startup.sh
Still get the 500 error.

Do you have any suggestions? Do I need to configure the manager app somehow? I'd like to use your session manager, but I know my teammates will try the /manager app. Thanks!

**Comment by ran-jit** [comment]
Hi @skehlet!

Which version of the session manager do you use?

**Comment by ran-jit** [comment]
Hi @skehlet!

I've reproduced the issue and working on it.

Thanks!

**Comment by ran-jit** [comment]
Hi @skehlet!

I've updated the changes in the [4.0](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/4.0) release. Please, update the new session manager in your tomcat and check the same.

I hope this helps. Thanks!

**Comment by skehlet** [comment]
I will test it tomorrow, thank you for the speedy fix! 🎉

**Comment by skehlet** [comment]
🙌 Looking good! Thanks so much and keep up the great work.

![image](https://user-images.githubusercontent.com/178873/81991598-82f7e900-95f6-11ea-8692-91996e80fd5e.png)
