### ISSUE TITLE
Support system variables in 3.0.1 version

### ISSUE THREAD

**Issue by damirabdul** [ran-jit/tomcat-cluster-redis-session-manager#55]
Hi, we want to use your library, but we couldn't use jedis v3, so we have chosen 3.0.1 version of session manager, but we also need system environment support feature, which was introduced only in 3.0.4 version. Is it possible to add this feature to 3.0.1 version please?

**Comment by ran-jit** [comment]
Hey @damirabdul,

I've created a new release ([3.0.1.1](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.1.1)) to support the Jedis 2x with the current features.

I hope this helps. Thanks!

**Comment by damirabdul** [comment]
Thank you, @ran-jit, for so fast answer and fix. It works perfect. Appreciate your work.
