### ISSUE TITLE
is there any reason to keep jedis 3.0 instead of jedis 3.3 ?

### ISSUE THREAD

**Issue by lepapareil** [ran-jit/tomcat-cluster-redis-session-manager#57]
Hi, looking at the latest packages built I see that the zip still contains jedis 3.0.1.
Is this a prerequisite or can i upgrade to the latest version in my tomcat ?

thks 👍

**Comment by ran-jit** [comment]
Hi @lepapareil,

The latest release [4.0](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/4.0)

[3.0.1.1](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.1.1) was created for https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/55 request.

Thanks!

**Comment by lepapareil** [comment]
I think I misspoke :(
I'm talking about the jedis library that you integrate in your zip package:

![image](https://user-images.githubusercontent.com/15672496/92108815-3c6a0c80-ede8-11ea-9687-4d2065e213da.png)

**Comment by ran-jit** [comment]
we tested the tomcat redis session manager with jedis 3.0.1 version. You can upgrade it to latest version.
